// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk5y9bkxzRN9CKKQJVOwhIDoR3vzF0CsU',
    appId: '1:965946138871:web:37b1116e09d4b986d2b3f2',
    messagingSenderId: '965946138871',
    projectId: 'blood-sea-57816',
    authDomain: 'blood-sea-57816.firebaseapp.com',
    storageBucket: 'blood-sea-57816.firebasestorage.app',
    measurementId: 'G-SEN977GTK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnfgoQrbLtKT8D-mDOY6zyYtLkU3ukFdY',
    appId: '1:965946138871:android:4ec7f372a350fbfad2b3f2',
    messagingSenderId: '965946138871',
    projectId: 'blood-sea-57816',
    storageBucket: 'blood-sea-57816.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaMNdkJU7SpqxYXWjvI8Sq-zKJ3RzKznE',
    appId: '1:965946138871:ios:5ad4ad4985ce14d0d2b3f2',
    messagingSenderId: '965946138871',
    projectId: 'blood-sea-57816',
    storageBucket: 'blood-sea-57816.firebasestorage.app',
    iosBundleId: 'com.example.bloodSea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaMNdkJU7SpqxYXWjvI8Sq-zKJ3RzKznE',
    appId: '1:965946138871:ios:5ad4ad4985ce14d0d2b3f2',
    messagingSenderId: '965946138871',
    projectId: 'blood-sea-57816',
    storageBucket: 'blood-sea-57816.firebasestorage.app',
    iosBundleId: 'com.example.bloodSea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk5y9bkxzRN9CKKQJVOwhIDoR3vzF0CsU',
    appId: '1:965946138871:web:eb189b1be737796ad2b3f2',
    messagingSenderId: '965946138871',
    projectId: 'blood-sea-57816',
    authDomain: 'blood-sea-57816.firebaseapp.com',
    storageBucket: 'blood-sea-57816.firebasestorage.app',
    measurementId: 'G-ZXHEEHSKJQ',
  );
}
